version: "3.9"
services:
  nginx:
    image: nginx:1.23.3
    container_name: test_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./repo:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl/
    working_dir: /var/www
    links:
      - php

  php:
    image: php:8.1.0-fpm
    container_name: test_php
    volumes:
      - ./repo:/var/www
    working_dir: /var/www
    links:
      - mysql

  mysql:
    image: mysql:5.7.36
    container_name: test_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password